"""Add system prompt and preference fields to Profile

Revision ID: b839125a7638
Revises: e0366a7e37a7
Create Date: 2025-03-05 19:13:10.070646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b839125a7638'
down_revision = 'e0366a7e37a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('food_preferences', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'additional_info')
    op.drop_column('profiles', 'food_preferences')
    op.drop_column('profiles', 'system_prompt')
    # ### end Alembic commands ### 