services:
  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-studio_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
    name: ${SECRET_KEY}
